### ISSUE TITLE
TODO: Enhancements for a new release

### ISSUE THREAD

**Issue by caike08** [BancoTalentosTCC/BancoTalentosTCC#122]
Thiago, CEO at Pandô apps, gave us some good points to work as enhancements, which I'm listing below: 

- [x] Cadastro do site da empresa não precisaria do HTTP:// no começo
- [x] Poupe o alerta de confirmação no cadastro da empresa
- [ ] Na pesquisa de alunos, ter um filtro por cidade ajudaria bastante
- [ ] Formatação da data com - e não /
- [x] Ao confirmar o cadastro de vaga, demorou para me exibir uma resposta... então tive tempo para clicar novamente. Com isso, cadastrei a mesma vaga duas vezes. **
- [x] Não encontrei como faço para desativar uma vaga que cadastrei
- [x] Seu nome não está nos créditos
- [x] identidade visual está bacana!

 ** For this one, we have something called "data-loading-text" which we disable the button after a request. We could use this on our form, and job creation :+1:
